version: '3.8'

services:
  was:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: fastapi
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb:
