"""empty message

Revision ID: 41cd3e74725f
Revises: 01b3ce8eb866
Create Date: 2024-11-03 02:36:00.030201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41cd3e74725f'
down_revision: Union[str, None] = '01b3ce8eb866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
